import pandas as pd
import calendar
import matplotlib.pyplot as plt
# ==============================
# 1. LOAD DATA
# ==============================

df = pd.read_csv("supermarket.csv")


# ==============================
# 2. DATA CLEANING
# ==============================

# Fill missing Payment Methods
df["Payment_Method"] = df["Payment_Method"].fillna("Unknown")

# Fill missing Customer Types
df["Customer_Type"] = df["Customer_Type"].fillna("Unknown")

# Fill missing Ratings
df["Rating"] = pd.to_numeric(df["Rating"], errors="coerce")

# Remove duplicate rows
df = df.drop_duplicates()


# ==============================
# 3. SAVE CLEANED DATA
# ==============================

df.to_csv("supermarket_cleaned.csv", index=False)


# ==============================
# 4. REVENUE ANALYSIS
# ==============================

# Total revenue
total_sum = df["Total"].sum()
print("Total Revenue:", total_sum)


# Revenue generated by each branch
branch_revenue = df.groupby("Branch")["Total"].sum()
max_branch = branch_revenue.idxmax()
max_revenue = branch_revenue.max()
city = df[df["Branch"] == max_branch]["City"].iloc[0]
print("Each Branch Revenue:")
print(branch_revenue)


# Branch with maximum revenue
print(
    "Maximum revenue generated from branch:",
    max_branch,"which is in the city: ",city,
    "and the value is:",
    max_revenue
)
# Category with maximum revenue 
category_revenue  = df.groupby("Product_Line")["Total"].sum()
print("The maximum revenue generated from the category:", category_revenue.idxmax(),"and the maximum revenue is: ",category_revenue.max())

#========================
# Customer analysis
# =======================
# 
customer = df.groupby("Customer_Type")["Total"].sum()
max_customer = customer.idxmax()
print("Maximum revenue is generated from the customer type: " , max_customer)
#=======HIGHEST PAYMENT TYPE=======

payment_method = df.groupby("Payment_Method")["Total"].sum()
print("The maximum revenue is generated from the payment type: " , payment_method.idxmax())

#===================================
df["Date"] = pd.to_datetime(df["Date"], dayfirst=True)


df["Month"] = df["Date"].dt.month
#======= Max revenue by month =======
month_revenue = df.groupby("Month")["Total"].sum()
max_month = month_revenue.idxmax()

print("Month with maximum revenue:", calendar.month_name[max_month])
print("Maximum revenue:", month_revenue.max())
#============================
customer_avg = df.groupby("Customer_Type")["Total"].mean()

print("Highest average transaction is for the customer of type: " , customer_avg.idxmax(),"and the value is: ", customer_avg.max())
print(customer_avg)
print(df["Customer_Type"].value_counts())
#=========Gender with max revenue ===========
gender_revenue = df.groupby("Gender")["Total"].sum()

print("Revenue by Gender:")
print(
    "Gender with maximum revenue:",
    gender_revenue.idxmax(),
    " and the Revenue is:",
    gender_revenue.max()
)
#==== Gender with avg revenue ========
gender_avg = df.groupby("Gender")["Total"].mean()
print(
    "Gender with highest average transaction:",
    gender_avg.idxmax(),
    "Average:",
    gender_avg.max()
)
#========category sells the most units============
product_quantity = df.groupby("Product_Line")["Quantity"].sum()
print(
    "Product category with highest quantity sold:",
    product_quantity.idxmax(),
    "Units:",
    product_quantity.max()
)
#=========== Product rating ============================
product_rating = df.groupby("Product_Line")["Rating"].mean()
print(
    "Product category with highest average rating:",
    product_rating.idxmax(),
    "Rating:",
    product_rating.max()
)
#=============== Product price avg =============
product_price = df.groupby("Product_Line")["Unit_Price"].mean()
print(
    "Product category with highest average unit price:",
    product_price.idxmax(),
    "Average price:",
    product_price.max()
)
# ================ Gross Income ====================
product_profit = df.groupby("Product_Line")["Gross_Income"].sum()
print(
    "Product category with highest gross income:",
    product_profit.idxmax(),
    "Gross income:",
    product_profit.max()
)
#=============== Which branch generates the most gross income===========
branch_profit = df.groupby("Branch")["Gross_Income"].sum()
max_branchp = branch_profit.idxmax()
city1 = df[df["Branch"] == max_branchp]["City"].iloc[0]
print("Branch with highest gross income:",
    branch_profit.idxmax(), "and the city is : " ,  city1,
    " and the Gross income:",
    branch_profit.max()
)
#============Which branch has the most transactions==========
branch_transactions = df["Branch"].value_counts()
print(
    "Branch with most transactions:",
    branch_transactions.idxmax(),
    "Transactions:",
    branch_transactions.max()
)
#================== On average, how much does a customer spend in each branch============
branch_avg = df.groupby("Branch")["Total"].mean()
print(
    "Branch with highest average transaction value:",
    branch_avg.idxmax(),
    "Average transaction:",
    branch_avg.max()
)
#===========Day-of-week analysis=========
df["Day"] = df["Date"].dt.day_name()
day_revenue = df.groupby("Day")["Total"].sum()
print(
    "Day with maximum revenue:",
    day_revenue.idxmax(),
    "and the Revenue is:",
    day_revenue.max()
)
df["Time"] = pd.to_datetime(df["Time"], format="%H:%M")
df["Hour"] = df["Time"].dt.hour
hourly_revenue = df.groupby("Hour")["Total"].sum()
print(
    "Hour with maximum revenue:",
    hourly_revenue.idxmax(),
    " and the revenue is:",
    hourly_revenue.max()
)
#=================== overall gross income =================
total_gross_income = df["Gross_Income"].sum()

print("Total Gross Income:", total_gross_income)

#============= Gross income percentage =========
total_revenue = df["Total"].sum()

gross_income_percentage = (total_gross_income / total_revenue) * 100

print("Total Revenue:", total_revenue)
print("Total Gross Income:", total_gross_income)
print("Gross Income Percentage:", gross_income_percentage)

category_cogs = df.groupby("Product_Line")["COGS"].sum()

print("COGS by product category:")
print(category_cogs)
#============== Which product category has the highest COGS ============
print(
    "Product category with highest COGS:",
    category_cogs.idxmax(),
    "and the COGS:",
    category_cogs.max()
)
#============= Gross income by payment method ==================
payment_profit = df.groupby("Payment_Method")["Gross_Income"].sum()
print(
    "Payment method with highest gross income:",
    payment_profit.idxmax(),
    "and the Gross income is:",
    payment_profit.max()
)

#==================== Correlation ===============
correlation = df["Quantity"].corr(df["Total"])
print("Correlation between Quantity and Total is: ",correlation)
correlation1 = df["Unit_Price"].corr(df["Total"])
print("Correlation between Unit Price and Total:", correlation1)

# ==============================
# 5. DATA VISUALIZATION
# ==============================
plt.bar(branch_revenue.index , branch_revenue.values,edgecolor = "black",color = "#A84242")
plt.title("Branch revenue")
plt.xlabel("Branches")
plt.ylabel("Revenue")
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()
# =======category revenue ==============
plt.barh(category_revenue.index,category_revenue.values,edgecolor = "black",color = "#3AAB60")
plt.title("category revenue")
plt.ylabel("Category")
plt.xlabel("Revenue")
plt.xticks(rotation= 0)
plt.tight_layout()
plt.show()
#======= customer revenue================

plt.bar(customer.index, customer.values, edgecolor="black", color="#2A6385")
plt.title("Customer Type Revenue")
plt.xlabel("Customer Type")
plt.ylabel("Revenue")
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

# =========== payment method ===========
plt.pie(payment_method.values,
        labels=payment_method.index,
        autopct="%1.1f%%",
        startangle=90)
plt.title("Revenue Share by Payment Method")
plt.tight_layout()
plt.show()

#========== Monthly revenue ==============
months = [calendar.month_abbr[i] for i in month_revenue.index]
plt.plot(months, month_revenue.values, marker="o")
plt.title("Monthly Revenue")
plt.xlabel("Month")
plt.ylabel("Revenue")
plt.tight_layout()
plt.show()
#==========Average Transaction by Customer Type==========
plt.bar(customer_avg.index, customer_avg.values,
        edgecolor="black",
        color="#4F1042")
plt.title("Average Transaction by Customer Type")
plt.xlabel("Customer Type")
plt.ylabel("Average Transaction")
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()
#============Revenue by Gender==============

plt.bar(gender_revenue.index, gender_revenue.values,
        edgecolor="black",
        color="#0E4C52")
plt.title("Revenue by Gender")
plt.xlabel("Gender")
plt.ylabel("Revenue")
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

# ============Average Transaction by Gender=========

plt.bar(gender_avg.index, gender_avg.values,
        edgecolor="black", color="#50440E")

plt.title("Average Transaction by Gender")
plt.xlabel("Gender")
plt.ylabel("Average Transaction")
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

#================== Quantity Sold by Product Category=====================
plt.barh(product_quantity.index, product_quantity.values,
         edgecolor="black", color="#3A440B")

plt.title("Quantity Sold by Product Category")
plt.xlabel("Quantity Sold")
plt.ylabel("Product Category")

plt.tight_layout()
plt.show()

#====================== Average Rating by Product Category ===================

plt.barh(product_rating.index, product_rating.values,
         edgecolor="black", color="#8595C1")
plt.title("Average Rating by Product Category")
plt.xlabel("Average Rating")
plt.ylabel("Product Category")
plt.tight_layout()
plt.show()

#====================== Average Unit Price by Product Category ===================

plt.barh(product_price.index, product_price.values,
         edgecolor="black", color="#8595C1")
plt.title("Average Unit Price by Product Category")
plt.xlabel("Average Unit Price")
plt.ylabel("Product Category")
plt.tight_layout()
plt.show()


#====================== Gross Income by Product Category ===================

plt.barh(product_profit.index, product_profit.values,
         edgecolor="black", color="#3A440B")
plt.title("Gross Income by Product Category")
plt.xlabel("Gross Income")
plt.ylabel("Product Category")
plt.tight_layout()
plt.show()


#====================== Gross Income by Branch ===================

plt.bar(branch_profit.index, branch_profit.values,
        edgecolor="black", color="#8595C1")
plt.title("Gross Income by Branch")
plt.xlabel("Branch")
plt.ylabel("Gross Income")
plt.tight_layout()
plt.show()


#====================== Number of Transactions by Branch ===================
plt.bar(branch_transactions.index, branch_transactions.values,
        edgecolor="black", color="#3A440B")
plt.title("Number of Transactions by Branch")
plt.xlabel("Branch")
plt.ylabel("Number of Transactions")
plt.tight_layout()
plt.show()


#====================== Average Transaction by Branch ===================

plt.bar(branch_avg.index, branch_avg.values,
        edgecolor="black", color="#8595C1")
plt.title("Average Transaction by Branch")
plt.xlabel("Branch")
plt.ylabel("Average Transaction")
plt.tight_layout()
plt.show()


#====================== Revenue by Day of Week ===================

days = [
    "Monday", "Tuesday", "Wednesday",
    "Thursday", "Friday", "Saturday", "Sunday"
]
day_revenue = day_revenue.reindex(days)
plt.bar(day_revenue.index, day_revenue.values,
        edgecolor="black", color="#3A440B")
plt.title("Revenue by Day of Week")
plt.xlabel("Day")
plt.ylabel("Revenue")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()


#====================== Revenue by Hour ===================

plt.plot(hourly_revenue.index, hourly_revenue.values,
         marker="o", color="#060E25")
plt.title("Revenue by Hour")
plt.xlabel("Hour")
plt.ylabel("Revenue")
plt.xticks(hourly_revenue.index)
plt.tight_layout()
plt.show()


#====================== COGS by Product Category ===================

plt.barh(category_cogs.index, category_cogs.values,
         edgecolor="black", color="#C9CFAF")
plt.title("COGS by Product Category")
plt.xlabel("COGS")
plt.ylabel("Product Category")
plt.tight_layout()
plt.show()


#====================== Gross Income by Payment Method ===================

plt.bar(payment_profit.index, payment_profit.values,
        edgecolor="black", color="#B42323")

plt.title("Gross Income by Payment Method")
plt.xlabel("Payment Method")
plt.ylabel("Gross Income")
plt.tight_layout()
plt.show()


#====================== Quantity vs Total ===================

plt.scatter(df["Quantity"], df["Total"],
            color="#3A440B")
plt.title("Quantity vs Total")
plt.xlabel("Quantity")
plt.ylabel("Total")
plt.tight_layout()
plt.show()

#====================== Unit Price vs Total ===================

plt.scatter(df["Unit_Price"], df["Total"],
            color="#408159")
plt.title("Unit Price vs Total")
plt.xlabel("Unit Price")
plt.ylabel("Total")
plt.tight_layout()
plt.show()

# ==============================
# 6. FINAL BUSINESS INSIGHTS
# ==============================

print("\n==============================")
print("       FINAL BUSINESS INSIGHTS")
print("==============================")

print("\n1. Branch Performance:")
print("Branch A generated the highest revenue with a total revenue of ₹430,953.90.")

print("\n2. Product Category Performance:")
print("Sports and Travel generated the highest revenue with ₹267,916.93.")

print("\n3. Customer Type Performance:")
print("Members generated the highest total revenue among the customer types.")

print("\n4. Payment Method Performance:")
print("Credit Card generated the highest total revenue among the payment methods.")

print("\n5. Monthly Performance:")
print("December recorded the highest monthly revenue with ₹118,216.74.")

print("\n6. Product Quantity:")
print("Health and Beauty had the highest quantity sold with 4,928 units.")

print("\n7. Product Gross Income:")
print("Sports and Travel generated the highest gross income with ₹76,547.69.")

print("\n8. Branch Transactions:")
print("Branch A had the highest number of transactions with 1,736 transactions.")

print("\n9. Day Performance:")
print("Saturday generated the highest daily revenue with ₹190,524.08.")

print("\n10. Hourly Performance:")
print("The highest hourly revenue was recorded at 7 PM, with ₹136,965.30.")

print("\n11. Overall Gross Income:")
print("The supermarket generated a total gross income of ₹353,386.86.")

print("\n12. Gross Income Percentage:")
print("Gross income represented approximately 28.57% of total revenue.")

print("\n13. Quantity and Revenue Relationship:")
print("Quantity and Total had a correlation of approximately 0.65,")
print("indicating a moderate positive relationship between quantity purchased and total transaction value.")

print("\n14. Unit Price and Revenue Relationship:")
print("Unit Price and Total had a correlation of approximately 0.69,")
print("indicating a moderate positive relationship between unit price and total transaction value.")

print("\n15. Customer Type Observation:")
print("Unknown customer type had the highest average transaction value at ₹258.72.")
print("However, there were only 74 Unknown customer transactions,")
print("so this result should be interpreted cautiously.")

print("\n==============================")
print("            CONCLUSION")
print("==============================")

print("The supermarket sales analysis provided insights into revenue,")
print("customer behavior, product performance, branch performance,")
print("payment methods, and sales patterns over time.")

print("Branch A generated the highest revenue and also had the highest")
print("number of transactions, while Sports and Travel was the highest")
print("revenue-generating and gross-income-generating product category.")

print("December and Saturday recorded the highest revenue among their")
print("respective time periods, while 7 PM recorded the highest hourly revenue.")

print("The correlation analysis showed moderate positive relationships")
print("between Quantity and Total, and between Unit Price and Total.")

print("Overall, the analysis demonstrates how Pandas can be used to")
print("clean, analyze, and extract meaningful business insights from sales data,")
print("while Matplotlib can be used to visualize those insights clearly.")